### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by cuent** [hadyelsahar/domain-shift-prediction#1]
Any update on when the code would be released?

**Comment by hadyelsahar** [comment]
Hey Cuent, Yes, we are in the end of the process, the code should be released ~2 weeks. 
Meanwhile let me know if there are specific parts of the paper you have problems implementing I can guide you through it.

**Comment by hadyelsahar** [comment]
Hey Cuent the code is available now at https://github.com/naver/domainshift-prediction

**Comment by cuent** [comment]
Thanks, 😄 I will dig into it
